version: '3.1'
networks:
  traefik-net: 
    external:
      name: traefik_net

services:
  cheddar:
    image: errm/cheese:cheddar
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.frontend.rule=Host:food.swarm;PathPrefixStripRegex:/api/cheeses/cheddar
        - traefik.port=80

  stilton:
    image: errm/cheese:stilton
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.frontend.rule=Host:food.swarm;PathPrefixStripRegex:/api/cheeses/stilton
        - traefik.port=80