version: '3.1'

networks:
  net:
    driver: overlay

services:
  traefik:
      image: traefik
      deploy:
        placement:
          constraints:
            - node.role == manager
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "80:80"
        - "8080:8080"
      networks:
        - net
      command: [--docker,
                --docker.swarmmode, 
                --docker.domain=swarm, 
                --docker.watch, 
                "--entryPoints=Name:http Address::80",
                "--defaultEntryPoints=http",
                --web,
                --web.metrics.prometheus]